/*
 Copyright (c) 2015,2016 Patrick Lai
*/
var CchsAppConfig=CchsAppConfig||{},CchsApp=function(g,n,b,t){var h=g.Route,p=n.Model,d=n.attr;b=b||g.Application.create();var m=t.api_ns||function(a){if(!a)return"gifts/api";"/"==a.substr(0,1)&&(a=a.substr(1));"/"==a.substr(-1)&&(a=a.substr(0,a.length-1));return""==a||"/"==a?"gifts/api":a+"/api"}(window.location.pathname),q=null,r=null,l=Math.max(5,Math.floor((window.innerHeight-300)/80)),e={getFullName:function(a,c){return c||a?c?a?c+" "+a:c:a:""},pickDept:function(a){var c="controller.dept",k=
"controller.model.dept_id",f=1;arguments.length>f&&(c=arguments[f++]);arguments.length>f&&(k=arguments[f++]);(f=a.get(c))&&!f.id&&(f=null);f=b.EntityPicker.create({what:"dept",title:"Pick Category",picked:f,entities:f?[f]:[],trigger:function(b,f){b&&(c&&a.set(c,b),k&&a.set(k,b.id))}});a.send("showModal","entity-picker",f)},pickDonor:function(a){var c=a.get("controller.donor"),c=b.EntityPicker.create({what:"donor",title:"Pick Supporter",picked:c,entities:c?[c]:[],fixup:function(a){a&&(a.name=e.getFullName(a.l_name,
a.f_name))},trigger:function(c,b){c&&(a.set("controller.donor",c),a.set("controller.model.donor_id",c.id))}});a.send("showModal","entity-picker",c)},pickItem:function(a){var c=a.get("controller.item"),c=b.EntityPicker.create({what:"item",title:"Pick Item",picked:c,entities:c?[c]:[],trigger:function(c,b){c&&(a.set("controller.item",c),a.set("controller.model.item_id",c.id))}});a.send("showModal","entity-picker",c)},getEntity:function(a,c,k){$.ajax({url:"/"+m+"/"+a+"s/"+c,dataType:"json"}).done(function(c){c=
c||{};c._err?console.log("API failed: "+JSON.stringify(c)):c[a]&&k(c[a])})},getWantingDepts:function(a,c){var k=2<arguments.length?arguments[2]:l;$.ajax({url:"/"+m+"/depts",dataType:"json",data:{pgsz:k,items:"count"}}).done(function(b){b=b||{};if(b.meta&&b.meta.total>k)e.getWantingDepts(a,c,2*k);else if(b.depts){var d=[];b.depts.forEach(function(a){a.items&&d.push(a)});c(d)}else b._err&&console.log("API failed: "+JSON.stringify(b))})},makeEditableObjectController:function(a){a=a||g.ObjectController;
return a.extend({isEditing:!1,isNotEditing:!0,actions:{edit:function(){this.set("isEditing",!0);this.set("isNotEditing",!1)},cancelEdit:function(){this.set("isEditing",!1);this.set("isNotEditing",!0);this.get("model").rollback()},finishEdit:function(){this.set("isEditing",!1);this.set("isNotEditing",!0);var a=this;this.get("model").save().then(function(b){a.send("refreshPage")})}}})}};b.setAccessToken=function(a){q=a};$.ajaxPrefilter(function(a){if(q){var c=0>a.url.indexOf("?")?"?":"&";a.url=a.url+
c+"_atoken="+encodeURIComponent(q)}});b.setDefaultGiver=function(a){r=a};b.ApplicationAdapter=n.RESTAdapter.extend({namespace:m});b.DateTransform=n.Transform.extend({deserialize:function(a){return a},serialize:function(a){return a}});b.Router.map(function(){this.resource("donors",function(){this.route("add");this.resource("donor",{path:":donor_id"})});this.resource("items",function(){this.route("add");this.resource("item",{path:":item_id"})});this.resource("depts",function(){this.route("add");this.resource("dept",
{path:":dept_id"})});this.resource("pledges",function(){this.route("add");this.resource("pledge",{path:":pledge_id"})})});b.ModalDialogComponent=g.Component.extend({actions:{ok:function(){this.$(".modal").modal("hide");this.sendAction("ok")}},show:function(){this.$(".modal").modal().on("hidden.bs.modal",function(){this.sendAction("close")}.bind(this))}.on("didInsertElement")});b.ApplicationRoute=h.extend({actions:{showModal:function(a,c){this.render(a,{into:"application",outlet:"modal",model:c})},
removeModal:function(){this.disconnectOutlet({outlet:"modal",parentView:"application"})}}});b.IndexRoute=h.extend({model:function(){var a=(new Date).getHours();return["<strong>"+(12>a?"Good morning!":18>a?"Good afternoon!":"Good evening!")+"</strong>"]}});b.DonorsRoute=h.extend({pgsz:l,pgno:1,searchStr:"",model:function(){var a={pgsz:this.pgsz,pgno:this.pgno};this.searchStr&&(a.search=this.searchStr);return this.store.find("donor",a)},setupController:function(a,c){this._super(a,c);var b=this.get("totalPages");
this.pgno>b&&(this.pgno=0<b?b:1);a.set("page",this.pgno);a.set("total",b);a.set("nameFilter",this.searchStr)},totalPages:function(){var a=this.store.metadataFor("donor");return Math.floor(((a.total||0)+this.pgsz-1)/this.pgsz)}.property("pgsz","searchStr","controller.model"),actions:{addDonor:function(){this.controller.transitionToRoute("donors.add")},delDonor:function(a){alert("TODO: delete donor")},pageFirst:function(){this.set("pgno",1);this.refresh()},pageNext:function(){if(!(this.get("controller.model.length")<
this.get("pgsz"))){var a=this.get("pgno");a>=this.get("totalPages")||(this.set("pgno",a+1),this.refresh())}},pagePrev:function(){var a=this.get("pgno");1>=a||(this.set("pgno",a-1),this.refresh())},pageLast:function(){var a=this.get("totalPages");this.set("pgno",a);this.refresh()},clearNameFilter:function(){this.controller.set("nameFilter","");this.send("applyNameFilter")},applyNameFilter:function(){var a=this.get("controller.nameFilter");this.get("searchStr")!=a&&(this.set("searchStr",a),this.send("pageFirst"))},
refreshPage:function(){this.refresh()}}});b.DonorsAddRoute=h.extend({model:function(){var a=this.store.createRecord("donor");a.set("l_name","");a.set("f_name","");a.set("email","");a.set("tags","");a.set("notes","");return a},actions:{add:function(a){var c=this;a.save().then(function(a){c.send("refreshPage");c.controller.transitionToRoute("donor",a.get("id"))})}}});b.DonorRoute=h.extend({setupController:function(a,c){this._super(a,c);a.set("isEditing",!1);a.set("isNotEditing",!0)},model:function(a){return this.store.find("donor",
a.donor_id)}});b.ItemsRoute=h.extend({pgsz:l,pgno:1,searchStr:"",deptMatch:null,model:function(){var a={pgsz:this.pgsz,pgno:this.pgno};this.searchStr&&(a.search=this.searchStr);this.deptMatch&&this.deptMatch.id&&(a.dept=this.deptMatch.id);return this.store.find("item",a)},setupController:function(a,c){this._super(a,c);this.deptMatch||(this.deptMatch=a.get("pseudoDeptAll"));var b=this.get("totalPages");this.pgno>b&&(this.pgno=0<b?b:1);var d=this;a.set("page",this.pgno);a.set("total",b);a.set("nameFilter",
this.searchStr);a.set("deptFilter",this.deptMatch);a.addObserver("deptFilter",function(){d.send("applyItemFilters")});!a.get("giver")&&r&&e.getEntity("donor",r,function(c){c&&(c.name=e.getFullName(c.l_name,c.f_name));a.set("giver",c)});e.getWantingDepts(this,function(c){var b=a.get("pseudoDeptAll");c.splice(0,0,b);var k=!1,d=a.get("deptFilter")||b;if(d.id){var f;for(f=0;f<c.length;++f)if(d.id==c[f].id){for(prop in c[f])a.set("deptFilter."+prop,c[f][prop]);c[f]=d;k=!0;break}}k||a.set("deptFilter",
b);a.set("deptChoices",c)})},totalPages:function(){var a=this.store.metadataFor("item");return Math.floor(((a.total||0)+this.pgsz-1)/this.pgsz)}.property("pgsz","searchStr","deptMatch.id","controller.model"),actions:{addItem:function(){this.controller.transitionToRoute("items.add")},delItem:function(a){alert("TODO: delete item")},contribToItem:function(a){if(a){var c=this.get("controller.giver");c&&(a=b.PledgeForm.create({donor:c,item:a,trigger:"submitPledge"}),this.send("showModal","pledge-form",
a))}},submitPledge:function(a){var c=a.get("item.price");if(c){var b=(a.get("count")+"").trim();if(b&&b.match(/^[1-9][0-9]*$/)){var d=b*c,c=a.get("donor.id"),e=a.get("item.id");if(c&&e){var g=this;$.ajax({url:"/"+m+"/donors/"+c+"/pledges",type:"POST",dataType:"json",data:{pledge:{item_id:e,amount:d}}}).done(function(a){a=a||{};if(a.pledge){a=a.pledge.id;g.refresh();var c="item#"+e+",gift#"+a;alert("Thank you! Your gift # is "+a);a="http://www.cchsrams.org/support-us/#amount="+d+"&memo="+encodeURIComponent(c);
window.location.assign(a)}else a._err&&console.log("API failed: "+JSON.stringify(a))})}}else alert("Please enter count.")}},pageFirst:function(){this.set("pgno",1);this.refresh()},pageNext:function(){if(!(this.get("controller.model.length")<this.get("pgsz"))){var a=this.get("pgno");a>=this.get("totalPages")||(this.set("pgno",a+1),this.refresh())}},pagePrev:function(){var a=this.get("pgno");1>=a||(this.set("pgno",a-1),this.refresh())},pageLast:function(){var a=this.get("totalPages");this.set("pgno",
a);this.refresh()},clearNameFilter:function(){this.controller.set("nameFilter","");this.send("applyItemFilters")},clearDeptFilter:function(){var a=this.controller.get("pseudoDeptAll");this.controller.set("deptFilter",a);this.send("applyItemFilters")},applyItemFilters:function(){var a=this.get("controller.nameFilter"),c=this.get("controller.deptFilter")||this.get("controller.pseudoDeptAll");if(this.get("searchStr")!=a||this.get("deptMatch.id")!=c.id)this.set("searchStr",a),this.set("deptMatch",c),
this.send("pageFirst")},pickDept:function(){this.get("controller");e.pickDept(this,"controller.deptFilter",null)},refreshPage:function(){this.refresh()}}});b.ItemsAddRoute=h.extend({model:function(){var a=this.store.createRecord("item");a.set("name","");return a},actions:{pickDept:function(){e.pickDept(this)},add:function(a){var c=this;a.save().then(function(a){c.send("refreshPage");c.controller.transitionToRoute("item",a.get("id"))})}}});b.ItemRoute=h.extend({setupController:function(a,c){this._super(a,
c);a.set("isEditing",!1);a.set("isNotEditing",!0);var b;(b=c.get("dept_id"))&&a.set("dept",this.store.find("dept",b))},model:function(a){return this.store.find("item",a.item_id)},actions:{pickDept:function(){e.pickDept(this)}}});b.DeptsRoute=h.extend({pgsz:l,pgno:1,searchStr:"",model:function(){var a={pgsz:this.pgsz,pgno:this.pgno};this.searchStr&&(a.search=this.searchStr);return this.store.find("dept",a)},setupController:function(a,c){this._super(a,c);var b=this.get("totalPages");this.pgno>b&&(this.pgno=
0<b?b:1);a.set("page",this.pgno);a.set("total",b);a.set("nameFilter",this.searchStr)},totalPages:function(){var a=this.store.metadataFor("dept");return Math.floor(((a.total||0)+this.pgsz-1)/this.pgsz)}.property("pgsz","searchStr","controller.model"),actions:{addDept:function(){this.controller.transitionToRoute("depts.add")},delDept:function(a){alert("TODO: delete dept")},pageFirst:function(){this.set("pgno",1);this.refresh()},pageNext:function(){if(!(this.get("controller.model.length")<this.get("pgsz"))){var a=
this.get("pgno");a>=this.get("totalPages")||(this.set("pgno",a+1),this.refresh())}},pagePrev:function(){var a=this.get("pgno");1>=a||(this.set("pgno",a-1),this.refresh())},pageLast:function(){var a=this.get("totalPages");this.set("pgno",a);this.refresh()},clearNameFilter:function(){this.controller.set("nameFilter","");this.send("applyNameFilter")},applyNameFilter:function(){var a=this.get("controller.nameFilter");this.get("searchStr")!=a&&(this.set("searchStr",a),this.send("pageFirst"))},refreshPage:function(){this.refresh()}}});
b.DeptsAddRoute=h.extend({model:function(){var a=this.store.createRecord("dept");a.set("name","");return a},actions:{add:function(a){var c=this;a.save().then(function(a){c.send("refreshPage");c.controller.transitionToRoute("dept",a.get("id"))})}}});b.DeptRoute=h.extend({setupController:function(a,c){this._super(a,c);a.set("isEditing",!1);a.set("isNotEditing",!0)},model:function(a){return this.store.find("dept",a.dept_id)}});b.PledgesRoute=h.extend({pgsz:l,pgno:1,searchStr:"",model:function(){var a=
{pgsz:this.pgsz,pgno:this.pgno};this.searchStr&&(a.search=this.searchStr);return this.store.find("pledge",a)},setupController:function(a,c){this._super(a,c);var b=this.get("totalPages");this.pgno>b&&(this.pgno=0<b?b:1);a.set("page",this.pgno);a.set("total",b);a.set("nameFilter",this.searchStr)},totalPages:function(){var a=this.store.metadataFor("pledge");return Math.floor(((a.total||0)+this.pgsz-1)/this.pgsz)}.property("pgsz","searchStr","controller.model"),actions:{addPledge:function(){this.controller.transitionToRoute("pledges.add")},
delPledge:function(a){alert("TODO: delete pledge")},pageFirst:function(){this.set("pgno",1);this.refresh()},pageNext:function(){if(!(this.get("controller.model.length")<this.get("pgsz"))){var a=this.get("pgno");a>=this.get("totalPages")||(this.set("pgno",a+1),this.refresh())}},pagePrev:function(){var a=this.get("pgno");1>=a||(this.set("pgno",a-1),this.refresh())},pageLast:function(){var a=this.get("totalPages");this.set("pgno",a);this.refresh()},clearNameFilter:function(){this.controller.set("nameFilter",
"");this.send("applyNameFilter")},applyNameFilter:function(){var a=this.get("controller.nameFilter");this.get("searchStr")!=a&&(this.set("searchStr",a),this.send("pageFirst"))},refreshPage:function(){this.refresh()}}});b.PledgesAddRoute=h.extend({model:function(){var a=this.store.createRecord("pledge");a.set("name","");return a},actions:{pickDonor:function(){e.pickDonor(this)},pickItem:function(){e.pickItem(this)},add:function(a){var c=this;a.save().then(function(a){c.send("refreshPage");c.controller.transitionToRoute("pledge",
a.get("id"))})}}});b.PledgeRoute=h.extend({setupController:function(a,c){this._super(a,c);a.set("isEditing",!1);a.set("isNotEditing",!0);var b;(b=c.get("donor_id"))&&a.set("donor",this.store.find("donor",b));(b=c.get("item_id"))&&a.set("item",this.store.find("item",b))},model:function(a){return this.store.find("pledge",a.pledge_id)},actions:{pickDonor:function(){e.pickDonor(this)},pickItem:function(){e.pickItem(this)}}});b.ModalDialog=g.Object.extend({title:"",main:"OK",other:"Close",ok:"done",close:"removeModal"});
b.Confirmation=b.ModalDialog.extend({title:"Confirmation Request",main:"No",other:"Yes",ok:"removeModal",close:"confirmed",trigger:null});b.EntityPicker=b.ModalDialog.extend({what:null,title:"Pick Entity",route:null,picked:null,entities:null,fixup:null,trigger:null});b.PledgeForm=b.ModalDialog.extend({title:"Pledge Form",main:"Confirm",other:"Cancel",ok:"confirmed",close:"removeModal",trigger:null,donor:null,item:null,count:1});b.Donor=p.extend({f_name:d("string"),l_name:d("string"),email:d("string"),
tags:d("string"),notes:d("string"),name:function(){var a=this.get("f_name"),c=this.get("l_name");return e.getFullName(c,a)}.property("f_name","l_name")});b.Item=p.extend({notes:d("string"),name:d("string"),description:d("string"),tags:d("string"),quantity:d("number"),price:d("number"),image_url:d("string"),detail_url:d("string"),dept_id:d("number"),pledged:d("number"),remain:function(){var a=this.get("total")||0,c=this.get("pledged")||0;return a>c?a-c:0}.property("total","pledged"),progress:function(){var a=
this.get("remain")||0;if(0>=a)return 100;var c=this.get("total")||0;return 100-Math.floor(100*a/c)}.property("remain","total"),total:function(){var a=this.get("quantity")||0,c=this.get("price")||0;return a*c}.property("price","quantity")});b.Dept=p.extend({name:d("string")});b.Pledge=p.extend({fulfilled:d("date"),tstamp:d("date"),lstamp:d("string"),donor_id:d("number"),item_id:d("number"),amount:d("number"),notes:d("string")});b.ConfirmationController=g.ObjectController.extend({actions:{confirmed:function(){var a=
this.get("model.trigger");a&&this.send(a,this.get("model"))}}});b.EntityPickerController=g.ObjectController.extend({searchStr:"",pgno:1,pgsz:l,actions:{pageFirst:function(){this.set("pgno",1);this.send("loadEntities")},pageNext:function(){var a=this.get("pgno");++a;this.set("pgno",a);this.send("loadEntities")},pagePrev:function(){var a=this.get("pgno");0>=a||(--a,this.set("pgno",a),this.send("loadEntities"))},search:function(){this.send("loadEntities")},loadEntities:function(){var a=this.get("model"),
c=a.what+"s";$.ajax({url:"/"+m+"/"+c,dataType:"json",data:{pgno:this.pgno,pgsz:this.pgsz,search:this.searchStr}}).done(function(b){b=b||{};if(b[c]){if(b=b[c]){var d=a.get("fixup");d&&b.forEach(d)}a.set("picked",null);a.set("entities",b)}else b._err&&console.log("API failed: "+JSON.stringify(b))})},pick:function(a){this.set("model.picked",a)},unpick:function(){this.set("model.picked",null)},done:function(){var a=this.get("model"),b=this.get("model.picked"),d=this.get("model.trigger");d&&d(b,a)}}});
b.PledgeFormController=g.ObjectController.extend({amount:function(){return this.get("model.item.price")*this.get("model.count")}.property("model.item.price","model.count"),actions:{confirmed:function(){var a=this.get("model.trigger");a&&this.send(a,this.get("model"))}}});b.ApplicationController=g.Controller.extend({isRouteDonors:function(){return"donors."==this.get("currentPath").substr(0,7)}.property("currentPath"),isRoutePledges:function(){return"pledges."==this.get("currentPath").substr(0,8)}.property("currentPath"),
isRouteItems:function(){return"items."==this.get("currentPath").substr(0,6)}.property("currentPath"),isRouteDepts:function(){return"depts."==this.get("currentPath").substr(0,6)}.property("currentPath"),isRouteIndex:function(){return"index"==this.get("currentPath").substr(0,5)}.property("currentPath")});b.DonorsController=g.ArrayController.extend({queryParams:["pgno","pgsz","search"],page:1,total:0,nameFilter:"",showOptions:!1,actions:{toggleShowOptions:function(){this.toggleProperty("showOptions")}}});
b.DonorsAddController=g.ObjectController.extend({});b.DonorController=e.makeEditableObjectController(b.DonorsAddController);b.ItemsController=g.ArrayController.extend({queryParams:["pgno","pgsz","dept","search"],page:1,total:0,pseudoDeptAll:{id:0,name:"(all)"},deptFilter:null,deptChoices:[],nameFilter:"",showOptions:!1,giver:null,actions:{pickGiver:function(){var a=this.get("giver"),c=this,a=b.EntityPicker.create({what:"donor",title:"Pick Giver",picked:a,entities:a?[a]:[],fixup:function(a){a&&(a.name=
e.getFullName(a.l_name,a.f_name))},trigger:function(a,b){a&&c.set("giver",a)}});this.send("showModal","entity-picker",a)},clearGiver:function(){this.set("giver",null)},toggleShowOptions:function(){this.toggleProperty("showOptions")}}});b.ItemsAddController=g.ObjectController.extend({needs:["dept"],dept:null});b.ItemController=e.makeEditableObjectController(b.ItemsAddController);b.DeptsController=g.ArrayController.extend({queryParams:["pgno","pgsz","search"],page:1,total:0,nameFilter:"",showOptions:!1,
actions:{toggleShowOptions:function(){this.toggleProperty("showOptions")}}});b.DeptsAddController=g.ObjectController.extend({});b.DeptController=e.makeEditableObjectController(b.DeptsAddController);b.PledgesController=g.ArrayController.extend({queryParams:["pgno","pgsz","donor_id"],page:1,total:0,donor:0,showOptions:!1,actions:{toggleShowOptions:function(){this.toggleProperty("showOptions")}}});b.PledgesAddController=g.ObjectController.extend({needs:["donor","item"],donor:null,item:null});b.PledgeController=
e.makeEditableObjectController(b.PledgesAddController);return b}(Ember,DS,CchsApp,CchsAppConfig);
