/*
 Copyright (c) 2015,2016 Patrick Lai
*/
var CchsAppConfig=CchsAppConfig||{},CchsApp=function(g,n,c,t){var k=g.Route,p=n.Model,d=n.attr;c=c||g.Application.create();var l=t.api_ns||function(a){if(!a)return"gifts/api";"/"==a.substr(0,1)&&(a=a.substr(1));"/"==a.substr(-1)&&(a=a.substr(0,a.length-1));return""==a||"/"==a?"gifts/api":a+"/api"}(window.location.pathname),q=null,r=null,m=Math.max(5,Math.floor((window.innerHeight-300)/80)),e={getFullName:function(a,b){return b||a?b?a?b+" "+a:b:a:""},pickDept:function(a){var b="controller.dept",h=
"controller.model.dept_id",f=1;arguments.length>f&&(b=arguments[f++]);arguments.length>f&&(h=arguments[f++]);(f=a.get(b))&&!f.id&&(f=null);f=c.EntityPicker.create({what:"dept",title:"Pick Category",picked:f,entities:f?[f]:[],trigger:function(c,f){c&&(b&&a.set(b,c),h&&a.set(h,c.id))}});a.send("showModal","entity-picker",f)},pickDonor:function(a){var b=a.get("controller.donor"),b=c.EntityPicker.create({what:"donor",title:"Pick Supporter",picked:b,entities:b?[b]:[],fixup:function(a){a&&(a.name=e.getFullName(a.l_name,
a.f_name))},trigger:function(b,c){b&&(a.set("controller.donor",b),a.set("controller.model.donor_id",b.id))}});a.send("showModal","entity-picker",b)},pickItem:function(a){var b=a.get("controller.item"),b=c.EntityPicker.create({what:"item",title:"Pick Item",picked:b,entities:b?[b]:[],trigger:function(b,c){b&&(a.set("controller.item",b),a.set("controller.model.item_id",b.id))}});a.send("showModal","entity-picker",b)},getEntity:function(a,b,h){$.ajax({url:"/"+l+"/"+a+"s/"+b,dataType:"json"}).done(function(b){b=
b||{};b._err?console.log("API failed: "+JSON.stringify(b)):b[a]&&h(b[a])})},getWantingDepts:function(a,b){var h=2<arguments.length?arguments[2]:m;$.ajax({url:"/"+l+"/depts",dataType:"json",data:{pgsz:h,items:"count"}}).done(function(c){c=c||{};if(c.meta&&c.meta.total>h)e.getWantingDepts(a,b,2*h);else if(c.depts){var d=[];c.depts.forEach(function(a){a.items&&d.push(a)});b(d)}else c._err&&console.log("API failed: "+JSON.stringify(c))})},makeEditableObjectController:function(a){a=a||g.ObjectController;
return a.extend({isEditing:!1,isNotEditing:!0,actions:{edit:function(){this.set("isEditing",!0);this.set("isNotEditing",!1)},cancelEdit:function(){this.set("isEditing",!1);this.set("isNotEditing",!0);this.get("model").rollback()},finishEdit:function(){this.set("isEditing",!1);this.set("isNotEditing",!0);var a=this;this.get("model").save().then(function(h){a.send("refreshPage")})}}})}};c.setAccessToken=function(a){q=a};$.ajaxPrefilter(function(a){if(q){var b=0>a.url.indexOf("?")?"?":"&";a.url=a.url+
b+"_atoken="+encodeURIComponent(q)}});c.setDefaultGiver=function(a){r=a};c.ApplicationAdapter=n.RESTAdapter.extend({namespace:l});c.DateTransform=n.Transform.extend({deserialize:function(a){return a},serialize:function(a){return a}});c.Router.map(function(){this.resource("donors",function(){this.route("add");this.resource("donor",{path:":donor_id"})});this.resource("items",function(){this.route("add");this.resource("item",{path:":item_id"})});this.resource("depts",function(){this.route("add");this.resource("dept",
{path:":dept_id"})});this.resource("pledges",function(){this.route("add");this.resource("pledge",{path:":pledge_id"})})});c.ModalDialogComponent=g.Component.extend({actions:{ok:function(){this.$(".modal").modal("hide");this.sendAction("ok")}},show:function(){this.$(".modal").modal().on("hidden.bs.modal",function(){this.sendAction("close")}.bind(this))}.on("didInsertElement")});c.ApplicationRoute=k.extend({actions:{showModal:function(a,b){this.render(a,{into:"application",outlet:"modal",model:b})},
removeModal:function(){this.disconnectOutlet({outlet:"modal",parentView:"application"})}}});c.IndexRoute=k.extend({model:function(){var a=(new Date).getHours();return["<strong>"+(12>a?"Good morning!":18>a?"Good afternoon!":"Good evening!")+"</strong>"]}});c.DonorsRoute=k.extend({pgsz:m,pgno:1,searchStr:"",model:function(){var a={pgsz:this.pgsz,pgno:this.pgno};this.searchStr&&(a.search=this.searchStr);return this.store.find("donor",a)},setupController:function(a,b){this._super(a,b);var h=this.get("totalPages");
this.pgno>h&&(this.pgno=0<h?h:1);a.set("page",this.pgno);a.set("total",h);a.set("nameFilter",this.searchStr)},totalPages:function(){var a=this.store.metadataFor("donor");return Math.floor(((a.total||0)+this.pgsz-1)/this.pgsz)}.property("pgsz","searchStr","controller.model"),actions:{addDonor:function(){this.controller.transitionToRoute("donors.add")},delDonor:function(a){alert("TODO: delete donor")},pageFirst:function(){this.set("pgno",1);this.refresh()},pageNext:function(){if(!(this.get("controller.model.length")<
this.get("pgsz"))){var a=this.get("pgno");a>=this.get("totalPages")||(this.set("pgno",a+1),this.refresh())}},pagePrev:function(){var a=this.get("pgno");1>=a||(this.set("pgno",a-1),this.refresh())},pageLast:function(){var a=this.get("totalPages");this.set("pgno",a);this.refresh()},clearNameFilter:function(){this.controller.set("nameFilter","");this.send("applyNameFilter")},applyNameFilter:function(){var a=this.get("controller.nameFilter");this.get("searchStr")!=a&&(this.set("searchStr",a),this.send("pageFirst"))},
refreshPage:function(){this.refresh()}}});c.DonorsAddRoute=k.extend({model:function(){var a=this.store.createRecord("donor");a.set("l_name","");a.set("f_name","");a.set("email","");a.set("tags","");a.set("notes","");return a},actions:{add:function(a){var b=this;a.save().then(function(a){b.send("refreshPage");b.controller.transitionToRoute("donor",a.get("id"))})}}});c.DonorRoute=k.extend({setupController:function(a,b){this._super(a,b);a.set("isEditing",!1);a.set("isNotEditing",!0)},model:function(a){return this.store.find("donor",
a.donor_id)}});c.ItemsRoute=k.extend({pgsz:m,pgno:1,searchStr:"",deptMatch:null,model:function(){var a={pgsz:this.pgsz,pgno:this.pgno};this.searchStr&&(a.search=this.searchStr);this.deptMatch&&this.deptMatch.id&&(a.dept=this.deptMatch.id);return this.store.find("item",a)},setupController:function(a,b){this._super(a,b);this.deptMatch||(this.deptMatch=a.get("pseudoDeptAll"));var c=this.get("totalPages");this.pgno>c&&(this.pgno=0<c?c:1);var d=this;a.set("page",this.pgno);a.set("total",c);a.set("nameFilter",
this.searchStr);a.set("deptFilter",this.deptMatch);a.addObserver("deptFilter",function(){d.send("applyItemFilters")});!a.get("giver")&&r&&e.getEntity("donor",r,function(b){b&&(b.name=e.getFullName(b.l_name,b.f_name));a.set("giver",b)});e.getWantingDepts(this,function(b){var c=a.get("pseudoDeptAll");b.splice(0,0,c);var h=!1,d=a.get("deptFilter")||c;if(d.id){var f;for(f=0;f<b.length;++f)if(d.id==b[f].id){for(prop in b[f])a.set("deptFilter."+prop,b[f][prop]);b[f]=d;h=!0;break}}h||a.set("deptFilter",
c);a.set("deptChoices",b)})},totalPages:function(){var a=this.store.metadataFor("item");return Math.floor(((a.total||0)+this.pgsz-1)/this.pgsz)}.property("pgsz","searchStr","deptMatch.id","controller.model"),actions:{addItem:function(){this.controller.transitionToRoute("items.add")},delItem:function(a){if(a&&confirm('Delete "'+a.get("name")+'"?')){var b=this;$.ajax({url:"/"+l+"/items/"+a.id,type:"DELETE"}).done(function(c){c=c||{};c.okay&&(alert("Item deleted."),b.store.find("item",a.id).then(function(a){a.unloadRecord();
b.send("refreshPage")}))})}},contribToItem:function(a){if(a){var b=this.get("controller.giver");b&&(a=c.PledgeForm.create({donor:b,item:a,trigger:"submitPledge"}),this.send("showModal","pledge-form",a))}},submitPledge:function(a){var b=a.get("item.price");if(b){var c=(a.get("count")+"").trim();if(c&&c.match(/^[1-9][0-9]*$/)){var d=c*b,b=a.get("donor.id"),e=a.get("item.id");if(b&&e){var g=this;$.ajax({url:"/"+l+"/donors/"+b+"/pledges",type:"POST",dataType:"json",data:{pledge:{item_id:e,amount:d}}}).done(function(a){a=
a||{};if(a.pledge){a=a.pledge.id;g.refresh();var b="item#"+e+",gift#"+a;alert("Thank you! Your gift # is "+a);a="http://www.cchsrams.org/support-us/#amount="+d+"&memo="+encodeURIComponent(b);window.location.assign(a)}else a._err&&console.log("API failed: "+JSON.stringify(a))})}}else alert("Please enter count.")}},pageFirst:function(){this.set("pgno",1);this.refresh()},pageNext:function(){if(!(this.get("controller.model.length")<this.get("pgsz"))){var a=this.get("pgno");a>=this.get("totalPages")||
(this.set("pgno",a+1),this.refresh())}},pagePrev:function(){var a=this.get("pgno");1>=a||(this.set("pgno",a-1),this.refresh())},pageLast:function(){var a=this.get("totalPages");this.set("pgno",a);this.refresh()},clearNameFilter:function(){this.controller.set("nameFilter","");this.send("applyItemFilters")},clearDeptFilter:function(){var a=this.controller.get("pseudoDeptAll");this.controller.set("deptFilter",a);this.send("applyItemFilters")},applyItemFilters:function(){var a=this.get("controller.nameFilter"),
b=this.get("controller.deptFilter")||this.get("controller.pseudoDeptAll");if(this.get("searchStr")!=a||this.get("deptMatch.id")!=b.id)this.set("searchStr",a),this.set("deptMatch",b),this.send("pageFirst")},pickDept:function(){this.get("controller");e.pickDept(this,"controller.deptFilter",null)},refreshPage:function(){this.refresh()}}});c.ItemsAddRoute=k.extend({model:function(){var a=this.store.createRecord("item");a.set("name","");return a},actions:{pickDept:function(){e.pickDept(this)},add:function(a){var b=
this;a.save().then(function(a){b.send("refreshPage");b.controller.transitionToRoute("item",a.get("id"))})}}});c.ItemRoute=k.extend({setupController:function(a,b){this._super(a,b);a.set("isEditing",!1);a.set("isNotEditing",!0);var c;(c=b.get("dept_id"))&&a.set("dept",this.store.find("dept",c))},model:function(a){return this.store.find("item",a.item_id)},actions:{pickDept:function(){e.pickDept(this)}}});c.DeptsRoute=k.extend({pgsz:m,pgno:1,searchStr:"",model:function(){var a={pgsz:this.pgsz,pgno:this.pgno};
this.searchStr&&(a.search=this.searchStr);return this.store.find("dept",a)},setupController:function(a,b){this._super(a,b);var c=this.get("totalPages");this.pgno>c&&(this.pgno=0<c?c:1);a.set("page",this.pgno);a.set("total",c);a.set("nameFilter",this.searchStr)},totalPages:function(){var a=this.store.metadataFor("dept");return Math.floor(((a.total||0)+this.pgsz-1)/this.pgsz)}.property("pgsz","searchStr","controller.model"),actions:{addDept:function(){this.controller.transitionToRoute("depts.add")},
delDept:function(a){alert("TODO: delete dept")},pageFirst:function(){this.set("pgno",1);this.refresh()},pageNext:function(){if(!(this.get("controller.model.length")<this.get("pgsz"))){var a=this.get("pgno");a>=this.get("totalPages")||(this.set("pgno",a+1),this.refresh())}},pagePrev:function(){var a=this.get("pgno");1>=a||(this.set("pgno",a-1),this.refresh())},pageLast:function(){var a=this.get("totalPages");this.set("pgno",a);this.refresh()},clearNameFilter:function(){this.controller.set("nameFilter",
"");this.send("applyNameFilter")},applyNameFilter:function(){var a=this.get("controller.nameFilter");this.get("searchStr")!=a&&(this.set("searchStr",a),this.send("pageFirst"))},refreshPage:function(){this.refresh()}}});c.DeptsAddRoute=k.extend({model:function(){var a=this.store.createRecord("dept");a.set("name","");return a},actions:{add:function(a){var b=this;a.save().then(function(a){b.send("refreshPage");b.controller.transitionToRoute("dept",a.get("id"))})}}});c.DeptRoute=k.extend({setupController:function(a,
b){this._super(a,b);a.set("isEditing",!1);a.set("isNotEditing",!0)},model:function(a){return this.store.find("dept",a.dept_id)}});c.PledgesRoute=k.extend({pgsz:m,pgno:1,searchStr:"",model:function(){var a={pgsz:this.pgsz,pgno:this.pgno};this.searchStr&&(a.search=this.searchStr);return this.store.find("pledge",a)},setupController:function(a,b){this._super(a,b);var c=this.get("totalPages");this.pgno>c&&(this.pgno=0<c?c:1);a.set("page",this.pgno);a.set("total",c);a.set("nameFilter",this.searchStr)},
totalPages:function(){var a=this.store.metadataFor("pledge");return Math.floor(((a.total||0)+this.pgsz-1)/this.pgsz)}.property("pgsz","searchStr","controller.model"),actions:{addPledge:function(){this.controller.transitionToRoute("pledges.add")},delPledge:function(a){alert("TODO: delete pledge")},pageFirst:function(){this.set("pgno",1);this.refresh()},pageNext:function(){if(!(this.get("controller.model.length")<this.get("pgsz"))){var a=this.get("pgno");a>=this.get("totalPages")||(this.set("pgno",
a+1),this.refresh())}},pagePrev:function(){var a=this.get("pgno");1>=a||(this.set("pgno",a-1),this.refresh())},pageLast:function(){var a=this.get("totalPages");this.set("pgno",a);this.refresh()},clearNameFilter:function(){this.controller.set("nameFilter","");this.send("applyNameFilter")},applyNameFilter:function(){var a=this.get("controller.nameFilter");this.get("searchStr")!=a&&(this.set("searchStr",a),this.send("pageFirst"))},refreshPage:function(){this.refresh()}}});c.PledgesAddRoute=k.extend({model:function(){var a=
this.store.createRecord("pledge");a.set("name","");return a},actions:{pickDonor:function(){e.pickDonor(this)},pickItem:function(){e.pickItem(this)},add:function(a){var b=this;a.save().then(function(a){b.send("refreshPage");b.controller.transitionToRoute("pledge",a.get("id"))})}}});c.PledgeRoute=k.extend({setupController:function(a,b){this._super(a,b);a.set("isEditing",!1);a.set("isNotEditing",!0);var c;(c=b.get("donor_id"))&&a.set("donor",this.store.find("donor",c));(c=b.get("item_id"))&&a.set("item",
this.store.find("item",c))},model:function(a){return this.store.find("pledge",a.pledge_id)},actions:{pickDonor:function(){e.pickDonor(this)},pickItem:function(){e.pickItem(this)}}});c.ModalDialog=g.Object.extend({title:"",main:"OK",other:"Close",ok:"done",close:"removeModal"});c.Confirmation=c.ModalDialog.extend({title:"Confirmation Request",main:"No",other:"Yes",ok:"removeModal",close:"confirmed",trigger:null});c.EntityPicker=c.ModalDialog.extend({what:null,title:"Pick Entity",route:null,picked:null,
entities:null,fixup:null,trigger:null});c.PledgeForm=c.ModalDialog.extend({title:"Pledge Form",main:"Confirm",other:"Cancel",ok:"confirmed",close:"removeModal",trigger:null,donor:null,item:null,count:1});c.Donor=p.extend({f_name:d("string"),l_name:d("string"),email:d("string"),tags:d("string"),notes:d("string"),name:function(){var a=this.get("f_name"),b=this.get("l_name");return e.getFullName(b,a)}.property("f_name","l_name")});c.Item=p.extend({notes:d("string"),name:d("string"),description:d("string"),
tags:d("string"),quantity:d("number"),price:d("number"),image_url:d("string"),detail_url:d("string"),dept_id:d("number"),pledged:d("number"),remain:function(){var a=this.get("total")||0,b=this.get("pledged")||0;return a>b?a-b:0}.property("total","pledged"),progress:function(){var a=this.get("remain")||0;if(0>=a)return 100;var b=this.get("total")||0;return 100-Math.floor(100*a/b)}.property("remain","total"),total:function(){var a=this.get("quantity")||0,b=this.get("price")||0;return a*b}.property("price",
"quantity")});c.Dept=p.extend({name:d("string")});c.Pledge=p.extend({fulfilled:d("date"),tstamp:d("date"),lstamp:d("string"),donor_id:d("number"),item_id:d("number"),amount:d("number"),notes:d("string")});c.ConfirmationController=g.ObjectController.extend({actions:{confirmed:function(){var a=this.get("model.trigger");a&&this.send(a,this.get("model"))}}});c.EntityPickerController=g.ObjectController.extend({searchStr:"",pgno:1,pgsz:m,actions:{pageFirst:function(){this.set("pgno",1);this.send("loadEntities")},
pageNext:function(){var a=this.get("pgno");++a;this.set("pgno",a);this.send("loadEntities")},pagePrev:function(){var a=this.get("pgno");0>=a||(--a,this.set("pgno",a),this.send("loadEntities"))},search:function(){this.send("loadEntities")},loadEntities:function(){var a=this.get("model"),b=a.what+"s";$.ajax({url:"/"+l+"/"+b,dataType:"json",data:{pgno:this.pgno,pgsz:this.pgsz,search:this.searchStr}}).done(function(c){c=c||{};if(c[b]){if(c=c[b]){var d=a.get("fixup");d&&c.forEach(d)}a.set("picked",null);
a.set("entities",c)}else c._err&&console.log("API failed: "+JSON.stringify(c))})},pick:function(a){this.set("model.picked",a)},unpick:function(){this.set("model.picked",null)},done:function(){var a=this.get("model"),b=this.get("model.picked"),c=this.get("model.trigger");c&&c(b,a)}}});c.PledgeFormController=g.ObjectController.extend({amount:function(){return this.get("model.item.price")*this.get("model.count")}.property("model.item.price","model.count"),actions:{confirmed:function(){var a=this.get("model.trigger");
a&&this.send(a,this.get("model"))}}});c.ApplicationController=g.Controller.extend({isRouteDonors:function(){return"donors."==this.get("currentPath").substr(0,7)}.property("currentPath"),isRoutePledges:function(){return"pledges."==this.get("currentPath").substr(0,8)}.property("currentPath"),isRouteItems:function(){return"items."==this.get("currentPath").substr(0,6)}.property("currentPath"),isRouteDepts:function(){return"depts."==this.get("currentPath").substr(0,6)}.property("currentPath"),isRouteIndex:function(){return"index"==
this.get("currentPath").substr(0,5)}.property("currentPath")});c.DonorsController=g.ArrayController.extend({queryParams:["pgno","pgsz","search"],page:1,total:0,nameFilter:"",showOptions:!1,actions:{toggleShowOptions:function(){this.toggleProperty("showOptions")}}});c.DonorsAddController=g.ObjectController.extend({});c.DonorController=e.makeEditableObjectController(c.DonorsAddController);c.ItemsController=g.ArrayController.extend({queryParams:["pgno","pgsz","dept","search"],page:1,total:0,pseudoDeptAll:{id:0,
name:"(all)"},deptFilter:null,deptChoices:[],nameFilter:"",showOptions:!1,giver:null,actions:{pickGiver:function(){var a=this.get("giver"),b=this,a=c.EntityPicker.create({what:"donor",title:"Pick Giver",picked:a,entities:a?[a]:[],fixup:function(a){a&&(a.name=e.getFullName(a.l_name,a.f_name))},trigger:function(a,c){a&&b.set("giver",a)}});this.send("showModal","entity-picker",a)},clearGiver:function(){this.set("giver",null)},toggleShowOptions:function(){this.toggleProperty("showOptions")}}});c.ItemsAddController=
g.ObjectController.extend({needs:["dept"],dept:null});c.ItemController=e.makeEditableObjectController(c.ItemsAddController);c.DeptsController=g.ArrayController.extend({queryParams:["pgno","pgsz","search"],page:1,total:0,nameFilter:"",showOptions:!1,actions:{toggleShowOptions:function(){this.toggleProperty("showOptions")}}});c.DeptsAddController=g.ObjectController.extend({});c.DeptController=e.makeEditableObjectController(c.DeptsAddController);c.PledgesController=g.ArrayController.extend({queryParams:["pgno",
"pgsz","donor_id"],page:1,total:0,donor:0,showOptions:!1,actions:{toggleShowOptions:function(){this.toggleProperty("showOptions")}}});c.PledgesAddController=g.ObjectController.extend({needs:["donor","item"],donor:null,item:null});c.PledgeController=e.makeEditableObjectController(c.PledgesAddController);return c}(Ember,DS,CchsApp,CchsAppConfig);
